import Head from 'next/head'
import React from 'react'
import { Navbar } from '../../molecules'

export const Header: React.FC = () => {
    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar />
        </>
    )
}
